### ISSUE TITLE
Name search issues

### ISSUE THREAD

**Issue by AustenGanley** [UoA-eResearch/eDNA#48]
Hi Warrick,
Here are some problems I've had when trying to search for taxon names. If I type in a name, it doesn't autocomplete like it used to do. That means that you have to actually scroll to the name, and don't have any obvious way of knowing whether that name is present or not (only tried this in the genus and species fields). 
If I do select a name, the fields above (higher taxonomic levels) are restricted to those that contain whatever I selected (eg. that genus). This is cool, but not always useful, so it would be good to have the option to turn this on or off (off meaning you can select any name from the higher taxonomic rank).
Finally, the display is buggy, in that if I end up not selecting something or try to delete the selection, I can't get rid of the drop-down box to leave it blank/see the other fields. I've attached a screenshot that might help explain what I mean.
A-
![Screen Shot 2019-10-10 at 10 03 18 AM](https://user-images.githubusercontent.com/56368828/66520286-5d2cd200-eb45-11e9-8e73-f94737b99523.png)

**Comment by warrickct** [comment]
Cheers Austen,

Will have a look at it when I get a chance.

**Comment by AustenGanley** [comment]
Hi Warrick,

Cool, thanks. Did you ever figure out why that python script wouldn’t work for me – does it work for you?

Cheers,
Austen

**Comment by warrickct** [comment]
Hey Austen,

Yep I managed to fix it. I think I sent you an email with the details about
the problem. If you download the most recent version it should work.

Cheers,

Warrick

**Comment by warrickct** [comment]
@AustenGanley 

Regarding the selection of higher taxonomic ranks being unfiltered based on existing lower taxonomic ranks: Since the database only returns results that match existing and sometimes more specific classifications, this would mean turning this off would mean you would get invalid taxonomic options to select. e.g. You'd be given the option to select bacteria as kingdom when Homosapien is the species. With that in mind is this feature still something you'd want to toggle?

**Comment by AustenGanley** [comment]
Hi Warrick,

Thanks for that. Yes, I think this would still be useful, in the case that you want to select an “OR” for the different combination of taxonomic groups for some reason.. Or maybe I’ve misunderstood how it works – if you add, say Homo sapiens, does this reset everything if you want to make another option, thus making what I say unnecessary?

And sorry about the previous mail – I’m not sure why I sent that – I’ve been able to get the script to work. As you say, some hits turn up, which is interesting..

Cheers,

Austen
